name: Tag Documentation Release

on:
  release:
    types:
    - published
  workflow_dispatch: {}

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:

    - name: Parse Event
      id: event
      run: |
        echo "::set-output name=tag::$(jq -r '.release.tag_name' "${GITHUB_EVENT_PATH}" | sed s/^v//)"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get Release Tag
      id: tag
      uses: paketo-buildpacks/github-config/actions/tag/tag-docs-submodule@main
      with:
        version: ${{ steps.event.outputs.tag }}

    - name: Create Docs Tag
      run: |
       git tag ${{ steps.tag.outputs.tag }}
       git push origin ${{ steps.tag.outputs.tag }}
